export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGIN_USER_GOOGLE = "LOGIN_USER_GOOGLE";
export const LOGIN_USER_ERROR_GOOGLE = "LOGIN_USER_ERROR_GOOGLE";

export const LOGOUT_USER = "LOGOUT_USER";

export const ISAUTHENTICATE = "ISAUTHENTICATE";

export const GET_MYACCOUT = "GET_MYACCOUT";
export const GET_MYACCOUT_ERROR = "GET_MYACCOUT_ERROR";
